/**
 * Auto-generated prop table data.
 * Generated by: node scripts/generate-prop-tables.mjs
 * Generated at: 2026-04-19T01:57:29.137Z
 * 
 * DO NOT EDIT MANUALLY — regenerate from TypeScript types.
 * Components: 76
 * Total props: 662
 */

export interface GeneratedProp {
  name: string;
  type: string;
  required: boolean;
  description: string;
  default?: string;
}

export const generatedProps: Record<string, GeneratedProp[]> = {
  "AadhaarInput": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Label text"
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "Current value (12 digits, formatted as XXXX XXXX XXXX)"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Called with raw 12-digit string"
    },
    {
      "name": "hint",
      "type": "string",
      "required": false,
      "description": "Hint text below input"
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false,
      "description": "Error message"
    }
  ],
  "Accordion": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "items",
      "type": "AccordionItem[]",
      "required": true,
      "description": "Accordion items"
    },
    {
      "name": "allowMultiple",
      "type": "boolean",
      "required": false,
      "description": "Allow multiple items to be open",
      "default": "false"
    },
    {
      "name": "value",
      "type": "string[]",
      "required": false,
      "description": "Controlled open items (keys)"
    },
    {
      "name": "defaultValue",
      "type": "string[]",
      "required": false,
      "description": "Default open items for uncontrolled mode"
    },
    {
      "name": "onChange",
      "type": "(openItems: string[]) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "collapsible",
      "type": "boolean",
      "required": false,
      "description": "Allow all items to be collapsed",
      "default": "true"
    }
  ],
  "AddressAutocompleteIndia": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is disabled"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "value",
      "type": "AddressValue",
      "required": false,
      "description": "Current address value"
    },
    {
      "name": "onChange",
      "type": "(value: AddressValue) => void",
      "required": false,
      "description": "Called when any address field changes"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Label text"
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false,
      "description": "Error message text"
    }
  ],
  "Alert": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "variant",
      "type": "StatusVariant",
      "required": false,
      "description": "Alert status variant",
      "default": "info"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "required": false,
      "description": "Alert title"
    },
    {
      "name": "description",
      "type": "ReactNode",
      "required": false,
      "description": "Alert description/message"
    },
    {
      "name": "icon",
      "type": "ReactNode",
      "required": false,
      "description": "Custom icon (overrides default status icon)"
    },
    {
      "name": "showIcon",
      "type": "boolean",
      "required": false,
      "description": "Whether to show icon",
      "default": "true"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": false,
      "description": "Close button handler (shows close button if provided)"
    },
    {
      "name": "closeLabel",
      "type": "string",
      "required": false,
      "description": "Close button accessible label",
      "default": "Close alert"
    }
  ],
  "ApplicationTracker": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "applicationId",
      "type": "string",
      "required": true,
      "description": "Application/reference ID"
    },
    {
      "name": "serviceName",
      "type": "string",
      "required": false,
      "description": "Service name"
    },
    {
      "name": "steps",
      "type": "TrackerStep[]",
      "required": true,
      "description": "Steps in the application journey"
    },
    {
      "name": "orientation",
      "type": "'horizontal' | 'vertical'",
      "required": false,
      "description": "Layout direction"
    }
  ],
  "AspectRatio": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "ratio",
      "type": "number | string",
      "required": false,
      "description": "Ratio as number (e.g. 16/9 = 1.777) or string \"16/9\""
    }
  ],
  "Autocomplete": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "options",
      "type": "AutocompleteOption[]",
      "required": true,
      "description": "Available options"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Input size",
      "default": "md"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "onSelect",
      "type": "(option: AutocompleteOption) => void",
      "required": false,
      "description": "Select handler"
    },
    {
      "name": "filterFn",
      "type": "(option: AutocompleteOption, query: string) => boolean",
      "required": false,
      "description": "Filter function"
    },
    {
      "name": "loading",
      "type": "boolean",
      "required": false,
      "description": "Loading state",
      "default": "false"
    },
    {
      "name": "emptyMessage",
      "type": "ReactNode",
      "required": false,
      "description": "Empty state message"
    },
    {
      "name": "maxOptions",
      "type": "number",
      "required": false,
      "description": "Maximum options to show",
      "default": "10"
    }
  ],
  "Avatar": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "src",
      "type": "string",
      "required": false,
      "description": "The src prop."
    },
    {
      "name": "alt",
      "type": "string",
      "required": false,
      "description": "The alt prop."
    },
    {
      "name": "size",
      "type": "'sm' | 'md' | 'lg' | 'xl'",
      "required": false,
      "description": "The size prop."
    },
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "The name prop."
    },
    {
      "name": "shape",
      "type": "'circle' | 'square'",
      "required": false,
      "description": "The shape prop."
    }
  ],
  "BackToTop": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "threshold",
      "type": "number",
      "required": false,
      "description": "Scroll threshold in pixels before button appears"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Accessible label"
    }
  ],
  "Badge": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "variant",
      "type": "StatusVariant | 'neutral'",
      "required": false,
      "description": "Badge variant/color",
      "default": "info"
    },
    {
      "name": "size",
      "type": "'sm' | 'md' | 'lg'",
      "required": false,
      "description": "Badge size",
      "default": "md"
    },
    {
      "name": "dot",
      "type": "boolean",
      "required": false,
      "description": "Whether to show a dot indicator",
      "default": "false"
    }
  ],
  "Breadcrumb": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "items",
      "type": "BreadcrumbItem[]",
      "required": true,
      "description": "Breadcrumb items"
    },
    {
      "name": "separator",
      "type": "ReactNode",
      "required": false,
      "description": "Separator between items",
      "default": "/"
    },
    {
      "name": "maxItems",
      "type": "number",
      "required": false,
      "description": "Maximum items to show before collapsing"
    },
    {
      "name": "collapseText",
      "type": "string",
      "required": false,
      "description": "Text for collapsed items",
      "default": "..."
    },
    {
      "name": "navProps",
      "type": "HTMLAttributes<HTMLElement>",
      "required": false,
      "description": "Additional props for nav element"
    }
  ],
  "Button": [
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "loading",
      "type": "boolean",
      "required": false,
      "description": "Loading state indicator",
      "default": "false"
    },
    {
      "name": "loadingText",
      "type": "string",
      "required": false,
      "description": "Accessible label for loading state"
    },
    {
      "name": "href",
      "type": "string",
      "required": false,
      "description": "Link href — used when as=\"a\""
    },
    {
      "name": "target",
      "type": "string",
      "required": false,
      "description": "Link target — used when as=\"a\""
    },
    {
      "name": "rel",
      "type": "string",
      "required": false,
      "description": "Link rel — used when as=\"a\""
    }
  ],
  "CalendarScheduler": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "selectedDate",
      "type": "string",
      "required": false,
      "description": "Currently selected date (ISO string, e.g. \"2025-01-15\")"
    },
    {
      "name": "onDateSelect",
      "type": "(date: string) => void",
      "required": false,
      "description": "Called when a date cell is clicked"
    },
    {
      "name": "availableDates",
      "type": "string[]",
      "required": false,
      "description": "Array of available/bookable dates (ISO strings)"
    },
    {
      "name": "minDate",
      "type": "string",
      "required": false,
      "description": "Earliest selectable date (ISO string)"
    },
    {
      "name": "maxDate",
      "type": "string",
      "required": false,
      "description": "Latest selectable date (ISO string)"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Accessible label for the calendar"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the calendar is disabled"
    }
  ],
  "Captcha": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "onVerify",
      "type": "(value: string) => void",
      "required": true,
      "description": "Called with the entered captcha value"
    },
    {
      "name": "length",
      "type": "number",
      "required": false,
      "description": "Length of captcha code"
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false,
      "description": "Error message"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Label"
    }
  ],
  "Card": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "variant",
      "type": "'elevated' | 'outlined' | 'filled'",
      "required": false,
      "description": "Card variant",
      "default": "elevated"
    },
    {
      "name": "clickable",
      "type": "boolean",
      "required": false,
      "description": "Whether the card is clickable/interactive",
      "default": "false"
    },
    {
      "name": "padding",
      "type": "'none' | 'sm' | 'md' | 'lg'",
      "required": false,
      "description": "Padding size",
      "default": "md"
    }
  ],
  "Center": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "minHeight",
      "type": "string | number",
      "required": false,
      "description": "Minimum height"
    },
    {
      "name": "inline",
      "type": "boolean",
      "required": false,
      "description": "Center inline (horizontal only)"
    }
  ],
  "ChartLibrary": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "type",
      "type": "ChartType",
      "required": false,
      "description": "Chart type"
    },
    {
      "name": "data",
      "type": "ChartDataPoint[]",
      "required": true,
      "description": "Data points to render"
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "description": "Chart title"
    },
    {
      "name": "height",
      "type": "number",
      "required": false,
      "description": "Chart height in pixels"
    },
    {
      "name": "colors",
      "type": "string[]",
      "required": false,
      "description": "Array of color strings for data points"
    }
  ],
  "Chatbot": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "description": "Title displayed in the chat header"
    },
    {
      "name": "messages",
      "type": "ChatMessage[]",
      "required": false,
      "description": "Array of chat messages"
    },
    {
      "name": "onSend",
      "type": "(text: string) => void",
      "required": false,
      "description": "Called when the user sends a message"
    },
    {
      "name": "open",
      "type": "boolean",
      "required": false,
      "description": "Whether the chat panel is open"
    },
    {
      "name": "onToggle",
      "type": "() => void",
      "required": false,
      "description": "Called when the toggle button is clicked"
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "description": "Placeholder text for the message input"
    }
  ],
  "Checkbox": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Checkbox label text"
    },
    {
      "name": "checked",
      "type": "boolean",
      "required": false,
      "description": "Whether the checkbox is checked"
    },
    {
      "name": "defaultChecked",
      "type": "boolean",
      "required": false,
      "description": "Default checked state for uncontrolled component"
    },
    {
      "name": "indeterminate",
      "type": "boolean",
      "required": false,
      "description": "Indeterminate state (for \"select all\" scenarios)",
      "default": "false"
    },
    {
      "name": "onChange",
      "type": "(event: ChangeEvent<HTMLInputElement>) => void",
      "required": false,
      "description": "Change handler"
    }
  ],
  "CodeBlock": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "code",
      "type": "string",
      "required": true,
      "description": "The code prop."
    },
    {
      "name": "language",
      "type": "string",
      "required": false,
      "description": "The language prop."
    },
    {
      "name": "filename",
      "type": "string",
      "required": false,
      "description": "The filename prop."
    },
    {
      "name": "showLineNumbers",
      "type": "boolean",
      "required": false,
      "description": "The showLineNumbers prop."
    },
    {
      "name": "copyable",
      "type": "boolean",
      "required": false,
      "description": "The copyable prop."
    }
  ],
  "Container": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "maxWidth",
      "type": "'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'full'",
      "required": false,
      "description": "Max width"
    },
    {
      "name": "centered",
      "type": "boolean",
      "required": false,
      "description": "Center content"
    },
    {
      "name": "padding",
      "type": "boolean",
      "required": false,
      "description": "Horizontal padding"
    }
  ],
  "DataGrid": [
    {
      "name": "columns",
      "type": "DataGridColumn<T>[]",
      "required": true,
      "description": "Column definitions"
    },
    {
      "name": "data",
      "type": "T[]",
      "required": true,
      "description": "Row data"
    },
    {
      "name": "rowKey",
      "type": "string",
      "required": true,
      "description": "Unique key field in data"
    },
    {
      "name": "onSort",
      "type": "(key: string, direction: SortDirection) => void",
      "required": false,
      "description": "Called when sort changes"
    },
    {
      "name": "sortKey",
      "type": "string",
      "required": false,
      "description": "Current sort column"
    },
    {
      "name": "sortDirection",
      "type": "SortDirection",
      "required": false,
      "description": "Current sort direction"
    },
    {
      "name": "loading",
      "type": "boolean",
      "required": false,
      "description": "Loading state"
    },
    {
      "name": "emptyMessage",
      "type": "string",
      "required": false,
      "description": "Empty state message"
    },
    {
      "name": "striped",
      "type": "boolean",
      "required": false,
      "description": "Whether rows are striped"
    },
    {
      "name": "hoverable",
      "type": "boolean",
      "required": false,
      "description": "Whether rows are hoverable"
    },
    {
      "name": "caption",
      "type": "string",
      "required": false,
      "description": "Caption for accessibility"
    }
  ],
  "DatePicker": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Input size",
      "default": "md"
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "Controlled value (ISO date string YYYY-MM-DD)"
    },
    {
      "name": "min",
      "type": "string",
      "required": false,
      "description": "Minimum date (ISO format YYYY-MM-DD)"
    },
    {
      "name": "max",
      "type": "string",
      "required": false,
      "description": "Maximum date (ISO format YYYY-MM-DD)"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Change handler"
    }
  ],
  "DescriptionList": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "items",
      "type": "DescriptionItem[]",
      "required": true,
      "description": "The items prop."
    },
    {
      "name": "layout",
      "type": "'vertical' | 'horizontal'",
      "required": false,
      "description": "Layout"
    },
    {
      "name": "striped",
      "type": "boolean",
      "required": false,
      "description": "Striped rows"
    }
  ],
  "Dialog": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "open",
      "type": "boolean",
      "required": true,
      "description": "Whether dialog is open"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": true,
      "description": "Close handler"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "required": false,
      "description": "Dialog title"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "Dialog content"
    },
    {
      "name": "description",
      "type": "ReactNode",
      "required": false,
      "description": "Optional description announced by assistive technology."
    },
    {
      "name": "footer",
      "type": "ReactNode",
      "required": false,
      "description": "Dialog footer actions"
    },
    {
      "name": "size",
      "type": "ComponentSize | 'xl' | 'full'",
      "required": false,
      "description": "Dialog size",
      "default": "md"
    },
    {
      "name": "closeOnBackdrop",
      "type": "boolean",
      "required": false,
      "description": "Close on backdrop click",
      "default": "true"
    },
    {
      "name": "closeOnEscape",
      "type": "boolean",
      "required": false,
      "description": "Close on escape key",
      "default": "true"
    },
    {
      "name": "showCloseButton",
      "type": "boolean",
      "required": false,
      "description": "Show close button",
      "default": "true"
    },
    {
      "name": "contentProps",
      "type": "HTMLAttributes<HTMLDivElement>",
      "required": false,
      "description": "Additional props for dialog content"
    },
    {
      "name": "backdropProps",
      "type": "HTMLAttributes<HTMLDivElement>",
      "required": false,
      "description": "Additional props for backdrop"
    }
  ],
  "DigitalSignature": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "onSign",
      "type": "(dataUrl: string) => void",
      "required": false,
      "description": "Called with the canvas data URL after signing"
    },
    {
      "name": "onClear",
      "type": "() => void",
      "required": false,
      "description": "Called when the signature is cleared"
    },
    {
      "name": "width",
      "type": "number",
      "required": false,
      "description": "Canvas width in pixels"
    },
    {
      "name": "height",
      "type": "number",
      "required": false,
      "description": "Canvas height in pixels"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Accessible label for the signature pad"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the signature pad is disabled"
    }
  ],
  "Divider": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "orientation",
      "type": "'horizontal' | 'vertical'",
      "required": false,
      "description": "Orientation"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Label text in the middle"
    },
    {
      "name": "spacing",
      "type": "'sm' | 'md' | 'lg'",
      "required": false,
      "description": "Spacing around divider"
    }
  ],
  "DocumentViewer": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "src",
      "type": "string",
      "required": true,
      "description": "Document source URL"
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "description": "Document title"
    },
    {
      "name": "type",
      "type": "DocumentType",
      "required": false,
      "description": "Type of document to display"
    },
    {
      "name": "height",
      "type": "number | string",
      "required": false,
      "description": "Viewer height"
    },
    {
      "name": "downloadable",
      "type": "boolean",
      "required": false,
      "description": "Whether the document can be downloaded"
    },
    {
      "name": "onDownload",
      "type": "() => void",
      "required": false,
      "description": "Called when download button is clicked"
    }
  ],
  "Drawer": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "open",
      "type": "boolean",
      "required": true,
      "description": "Whether drawer is open"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": true,
      "description": "Close handler"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "required": false,
      "description": "Drawer title"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "Drawer content"
    },
    {
      "name": "footer",
      "type": "ReactNode",
      "required": false,
      "description": "Drawer footer actions"
    },
    {
      "name": "placement",
      "type": "DrawerPlacement",
      "required": false,
      "description": "Drawer placement",
      "default": "right"
    },
    {
      "name": "size",
      "type": "string | number",
      "required": false,
      "description": "Drawer size (width for left/right, height for top/bottom)",
      "default": "400px"
    },
    {
      "name": "closeOnBackdrop",
      "type": "boolean",
      "required": false,
      "description": "Close on backdrop click",
      "default": "true"
    },
    {
      "name": "closeOnEscape",
      "type": "boolean",
      "required": false,
      "description": "Close on escape key",
      "default": "true"
    },
    {
      "name": "showCloseButton",
      "type": "boolean",
      "required": false,
      "description": "Show close button",
      "default": "true"
    },
    {
      "name": "contentProps",
      "type": "HTMLAttributes<HTMLDivElement>",
      "required": false,
      "description": "Additional props for drawer content"
    },
    {
      "name": "backdropProps",
      "type": "HTMLAttributes<HTMLDivElement>",
      "required": false,
      "description": "Additional props for backdrop"
    }
  ],
  "Dropdown": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Label text"
    },
    {
      "name": "options",
      "type": "DropdownOption[]",
      "required": true,
      "description": "Options list"
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "Selected value"
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "description": "Placeholder when no value selected"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Size"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Disabled"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Required"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state"
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false,
      "description": "Error message"
    },
    {
      "name": "hint",
      "type": "string",
      "required": false,
      "description": "Hint text"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field id"
    },
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name"
    }
  ],
  "EmptyState": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "title",
      "type": "string",
      "required": true,
      "description": "Title text"
    },
    {
      "name": "description",
      "type": "string",
      "required": false,
      "description": "Description text"
    },
    {
      "name": "icon",
      "type": "ReactNode",
      "required": false,
      "description": "Icon or illustration to display"
    },
    {
      "name": "action",
      "type": "ReactNode",
      "required": false,
      "description": "Primary action button"
    },
    {
      "name": "secondaryAction",
      "type": "ReactNode",
      "required": false,
      "description": "Secondary action"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Size variant"
    }
  ],
  "FeedbackRatingWidget": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "value",
      "type": "number",
      "required": false,
      "description": "Current rating (1-5)"
    },
    {
      "name": "onChange",
      "type": "(rating: number) => void",
      "required": false,
      "description": "The onChange prop."
    },
    {
      "name": "max",
      "type": "number",
      "required": false,
      "description": "Max stars"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "The label prop."
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "The disabled prop."
    },
    {
      "name": "size",
      "type": "'sm' | 'md' | 'lg'",
      "required": false,
      "description": "The size prop."
    }
  ],
  "Field": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Whether the field has an error Automatically adds error styling to child components",
      "default": "false"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is disabled",
      "default": "false"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Shared control id used to connect label, hint, and error text. If omitted, Field generates one automatically."
    },
    {
      "name": "label",
      "type": "ReactNode",
      "required": false,
      "description": "Optional label content rendered above the field control."
    },
    {
      "name": "hint",
      "type": "ReactNode",
      "required": false,
      "description": "Optional helper text rendered below the field control."
    },
    {
      "name": "errorText",
      "type": "ReactNode",
      "required": false,
      "description": "Optional error message rendered below the field control. When present, the field is treated as invalid."
    }
  ],
  "FileUpload": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "onChange",
      "type": "(files: File[]) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "accept",
      "type": "string",
      "required": false,
      "description": "Accept file types"
    },
    {
      "name": "multiple",
      "type": "boolean",
      "required": false,
      "description": "Allow multiple files",
      "default": "false"
    },
    {
      "name": "maxSize",
      "type": "number",
      "required": false,
      "description": "Maximum file size in bytes"
    },
    {
      "name": "maxFiles",
      "type": "number",
      "required": false,
      "description": "Maximum number of files"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Disabled state",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state",
      "default": "false"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": false,
      "description": "Custom upload area content"
    },
    {
      "name": "showFileList",
      "type": "boolean",
      "required": false,
      "description": "Show file list",
      "default": "true"
    },
    {
      "name": "validator",
      "type": "(file: File) => string | null",
      "required": false,
      "description": "File validation function"
    }
  ],
  "Flex": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "direction",
      "type": "'row' | 'row-reverse' | 'column' | 'column-reverse'",
      "required": false,
      "description": "The direction prop."
    },
    {
      "name": "align",
      "type": "'start' | 'center' | 'end' | 'stretch' | 'baseline'",
      "required": false,
      "description": "The align prop."
    },
    {
      "name": "justify",
      "type": "'start' | 'center' | 'end' | 'between' | 'around' | 'evenly'",
      "required": false,
      "description": "The justify prop."
    },
    {
      "name": "wrap",
      "type": "'nowrap' | 'wrap' | 'wrap-reverse'",
      "required": false,
      "description": "The wrap prop."
    },
    {
      "name": "gap",
      "type": "number | string",
      "required": false,
      "description": "The gap prop."
    },
    {
      "name": "inline",
      "type": "boolean",
      "required": false,
      "description": "The inline prop."
    }
  ],
  "Footer": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "sections",
      "type": "FooterSection[]",
      "required": false,
      "description": "The sections prop."
    },
    {
      "name": "copyright",
      "type": "string",
      "required": false,
      "description": "The copyright prop."
    },
    {
      "name": "logo",
      "type": "ReactNode",
      "required": false,
      "description": "The logo prop."
    },
    {
      "name": "socialLinks",
      "type": "ReactNode",
      "required": false,
      "description": "The socialLinks prop."
    }
  ],
  "FormBuilder": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "fields",
      "type": "FormFieldConfig[]",
      "required": true,
      "description": "Field configurations"
    },
    {
      "name": "onSubmit",
      "type": "(values: Record<string, string>) => void",
      "required": true,
      "description": "Called on form submit with field values"
    },
    {
      "name": "submitLabel",
      "type": "string",
      "required": false,
      "description": "Submit button text"
    },
    {
      "name": "loading",
      "type": "boolean",
      "required": false,
      "description": "Whether form is submitting"
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "description": "Form title"
    },
    {
      "name": "description",
      "type": "string",
      "required": false,
      "description": "Form description"
    }
  ],
  "Grid": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "columns",
      "type": "number | string",
      "required": false,
      "description": "The columns prop."
    },
    {
      "name": "gap",
      "type": "number | string",
      "required": false,
      "description": "The gap prop."
    },
    {
      "name": "rowGap",
      "type": "number | string",
      "required": false,
      "description": "The rowGap prop."
    },
    {
      "name": "columnGap",
      "type": "number | string",
      "required": false,
      "description": "The columnGap prop."
    },
    {
      "name": "align",
      "type": "'start' | 'center' | 'end' | 'stretch'",
      "required": false,
      "description": "The align prop."
    }
  ],
  "Header": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "title",
      "type": "string",
      "required": true,
      "description": "Site/service title"
    },
    {
      "name": "logo",
      "type": "ReactNode",
      "required": false,
      "description": "Logo element"
    },
    {
      "name": "navItems",
      "type": "NavItem[]",
      "required": false,
      "description": "Navigation items"
    },
    {
      "name": "actions",
      "type": "ReactNode",
      "required": false,
      "description": "Right-side actions (e.g. language selector, login button)"
    },
    {
      "name": "sticky",
      "type": "boolean",
      "required": false,
      "description": "Sticky header"
    }
  ],
  "Input": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "value",
      "type": "T",
      "required": false,
      "description": "Controlled value"
    },
    {
      "name": "defaultValue",
      "type": "T",
      "required": false,
      "description": "Default value for uncontrolled mode"
    },
    {
      "name": "onChange",
      "type": "(value: T) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Input size",
      "default": "md"
    },
    {
      "name": "type",
      "type": "'text' | 'email' | 'password' | 'tel' | 'url' | 'search' | 'number'",
      "required": false,
      "description": "Input type",
      "default": "text"
    },
    {
      "name": "iconBefore",
      "type": "ReactNode",
      "required": false,
      "description": "Icon to display before input text"
    },
    {
      "name": "iconAfter",
      "type": "ReactNode",
      "required": false,
      "description": "Icon to display after input text"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "required": false,
      "description": "Render as full width input",
      "default": "false"
    }
  ],
  "LanguageSelector": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "languages",
      "type": "Language[]",
      "required": true,
      "description": "The languages prop."
    },
    {
      "name": "value",
      "type": "string",
      "required": true,
      "description": "The value prop."
    },
    {
      "name": "onChange",
      "type": "(code: string) => void",
      "required": true,
      "description": "The onChange prop."
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "The label prop."
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "The disabled prop."
    }
  ],
  "List": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "items",
      "type": "ListItem[]",
      "required": true,
      "description": "The items prop."
    },
    {
      "name": "dividers",
      "type": "boolean",
      "required": false,
      "description": "Dividers between items"
    },
    {
      "name": "ordered",
      "type": "boolean",
      "required": false,
      "description": "Ordered list"
    },
    {
      "name": "emptyMessage",
      "type": "string",
      "required": false,
      "description": "Empty state message"
    }
  ],
  "MapLocationPicker": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "latitude",
      "type": "number",
      "required": false,
      "description": "Latitude coordinate"
    },
    {
      "name": "longitude",
      "type": "number",
      "required": false,
      "description": "Longitude coordinate"
    },
    {
      "name": "onChange",
      "type": "(coords: { latitude: number",
      "required": false,
      "description": "Called when location changes"
    }
  ],
  "Menu": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "items",
      "type": "MenuItem[]",
      "required": true,
      "description": "Menu items"
    },
    {
      "name": "trigger",
      "type": "ReactNode",
      "required": true,
      "description": "Trigger element"
    },
    {
      "name": "placement",
      "type": "MenuPlacement",
      "required": false,
      "description": "Menu placement",
      "default": "bottom-start"
    },
    {
      "name": "open",
      "type": "boolean",
      "required": false,
      "description": "Controlled open state"
    },
    {
      "name": "defaultOpen",
      "type": "boolean",
      "required": false,
      "description": "Default open state"
    },
    {
      "name": "onOpenChange",
      "type": "(open: boolean) => void",
      "required": false,
      "description": "Open state change handler"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Disabled state",
      "default": "false"
    }
  ],
  "Modal": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "open",
      "type": "boolean",
      "required": true,
      "description": "The open prop."
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": true,
      "description": "The onClose prop."
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "description": "The title prop."
    },
    {
      "name": "description",
      "type": "string",
      "required": false,
      "description": "The description prop."
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "The size prop."
    },
    {
      "name": "closeOnOverlay",
      "type": "boolean",
      "required": false,
      "description": "The closeOnOverlay prop."
    }
  ],
  "OTPInput": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "length",
      "type": "number",
      "required": false,
      "description": "Number of OTP digits",
      "default": "6"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "onComplete",
      "type": "(value: string) => void",
      "required": false,
      "description": "Complete handler (called when all digits are entered)"
    },
    {
      "name": "type",
      "type": "'text' | 'number' | 'tel'",
      "required": false,
      "description": "Input type",
      "default": "text"
    },
    {
      "name": "autoFocus",
      "type": "boolean",
      "required": false,
      "description": "Auto focus first input",
      "default": "true"
    }
  ],
  "PANCardInput": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "The label prop."
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "Current value (e.g. \"ABCDE1234F\")"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Called with uppercase PAN string"
    },
    {
      "name": "hint",
      "type": "string",
      "required": false,
      "description": "The hint prop."
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false,
      "description": "The errorText prop."
    }
  ],
  "Pagination": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "totalPages",
      "type": "number",
      "required": true,
      "description": "Total number of pages"
    },
    {
      "name": "siblingCount",
      "type": "number",
      "required": false,
      "description": "Number of page buttons to show",
      "default": "7"
    },
    {
      "name": "showFirstLast",
      "type": "boolean",
      "required": false,
      "description": "Show first/last buttons",
      "default": "true"
    },
    {
      "name": "showPrevNext",
      "type": "boolean",
      "required": false,
      "description": "Show previous/next buttons",
      "default": "true"
    },
    {
      "name": "variant",
      "type": "PaginationVariant",
      "required": false,
      "description": "Visual variant",
      "default": "default"
    },
    {
      "name": "onChange",
      "type": "(page: number) => void",
      "required": false,
      "description": "Page change handler"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Disabled state",
      "default": "false"
    },
    {
      "name": "showPageInfo",
      "type": "boolean",
      "required": false,
      "description": "Show page info text (e.g., \"Page 1 of 10\")",
      "default": "false"
    },
    {
      "name": "labels",
      "type": "{ first?: string",
      "required": false,
      "description": "Custom labels"
    },
    {
      "name": "previous",
      "type": "string",
      "required": false,
      "description": "The previous prop."
    },
    {
      "name": "next",
      "type": "string",
      "required": false,
      "description": "The next prop."
    },
    {
      "name": "last",
      "type": "string",
      "required": false,
      "description": "The last prop."
    },
    {
      "name": "pageInfo",
      "type": "(current: number, total: number) => string",
      "required": false,
      "description": "The pageInfo prop."
    }
  ],
  "PaymentGateway": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "amount",
      "type": "number",
      "required": true,
      "description": "Payment amount"
    },
    {
      "name": "merchantName",
      "type": "string",
      "required": true,
      "description": "Merchant display name"
    },
    {
      "name": "upiId",
      "type": "string",
      "required": true,
      "description": "UPI ID for payment"
    },
    {
      "name": "onSuccess",
      "type": "() => void",
      "required": false,
      "description": "Called on successful payment"
    },
    {
      "name": "onFailure",
      "type": "(error: string) => void",
      "required": false,
      "description": "Called on payment failure"
    },
    {
      "name": "currency",
      "type": "string",
      "required": false,
      "description": "Currency code"
    }
  ],
  "Popover": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "content",
      "type": "ReactNode",
      "required": true,
      "description": "Popover content"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "Element that triggers the popover"
    },
    {
      "name": "placement",
      "type": "PopoverPlacement",
      "required": false,
      "description": "Popover placement",
      "default": "bottom"
    },
    {
      "name": "trigger",
      "type": "PopoverTrigger",
      "required": false,
      "description": "Trigger type",
      "default": "click"
    },
    {
      "name": "open",
      "type": "boolean",
      "required": false,
      "description": "Controlled open state"
    },
    {
      "name": "defaultOpen",
      "type": "boolean",
      "required": false,
      "description": "Default open state"
    },
    {
      "name": "onOpenChange",
      "type": "(open: boolean) => void",
      "required": false,
      "description": "Open state change handler"
    },
    {
      "name": "showArrow",
      "type": "boolean",
      "required": false,
      "description": "Show arrow",
      "default": "true"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "required": false,
      "description": "Popover title"
    }
  ],
  "Progress": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "value",
      "type": "number",
      "required": true,
      "description": "Progress value (0-100)"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Progress size",
      "default": "md"
    },
    {
      "name": "variant",
      "type": "StatusVariant",
      "required": false,
      "description": "Progress variant",
      "default": "info"
    },
    {
      "name": "showLabel",
      "type": "boolean",
      "required": false,
      "description": "Show label",
      "default": "false"
    },
    {
      "name": "labelFormatter",
      "type": "(value: number) => string",
      "required": false,
      "description": "Custom label formatter"
    },
    {
      "name": "indeterminate",
      "type": "boolean",
      "required": false,
      "description": "Indeterminate state (loading animation)",
      "default": "false"
    }
  ],
  "QRCode": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "value",
      "type": "string",
      "required": true,
      "description": "Data to encode"
    },
    {
      "name": "size",
      "type": "number",
      "required": false,
      "description": "Size in pixels"
    },
    {
      "name": "fgColor",
      "type": "string",
      "required": false,
      "description": "Foreground color"
    },
    {
      "name": "bgColor",
      "type": "string",
      "required": false,
      "description": "Background color"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Accessible label"
    }
  ],
  "Radio": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Radio label text"
    },
    {
      "name": "value",
      "type": "string",
      "required": true,
      "description": "Radio value"
    },
    {
      "name": "checked",
      "type": "boolean",
      "required": false,
      "description": "Whether the radio is checked"
    },
    {
      "name": "defaultChecked",
      "type": "boolean",
      "required": false,
      "description": "Default checked state for uncontrolled component"
    },
    {
      "name": "onChange",
      "type": "(event: ChangeEvent<HTMLInputElement>) => void",
      "required": false,
      "description": "Change handler"
    }
  ],
  "Rating": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "max",
      "type": "number",
      "required": false,
      "description": "Maximum rating value",
      "default": "5"
    },
    {
      "name": "allowHalf",
      "type": "boolean",
      "required": false,
      "description": "Allow half stars",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Read-only mode",
      "default": "false"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Disabled state",
      "default": "false"
    },
    {
      "name": "size",
      "type": "'sm' | 'md' | 'lg'",
      "required": false,
      "description": "Rating size",
      "default": "md"
    },
    {
      "name": "onChange",
      "type": "(value: number) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "onHover",
      "type": "(value: number | null) => void",
      "required": false,
      "description": "Hover handler"
    },
    {
      "name": "icon",
      "type": "string",
      "required": false,
      "description": "Custom icon"
    },
    {
      "name": "showLabel",
      "type": "boolean",
      "required": false,
      "description": "Show label",
      "default": "false"
    },
    {
      "name": "labelFormatter",
      "type": "(value: number) => string",
      "required": false,
      "description": "Custom label formatter"
    }
  ],
  "RichTextEditor": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "HTML content value"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Called when content changes"
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "description": "Placeholder text"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the editor is disabled"
    },
    {
      "name": "minHeight",
      "type": "number | string",
      "required": false,
      "description": "Minimum height of the editor"
    },
    {
      "name": "toolbar",
      "type": "ToolbarAction[]",
      "required": false,
      "description": "Toolbar actions to display"
    }
  ],
  "SearchBar": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Input size",
      "default": "md"
    },
    {
      "name": "onSearch",
      "type": "(value: string) => void",
      "required": false,
      "description": "Search handler"
    },
    {
      "name": "onClear",
      "type": "() => void",
      "required": false,
      "description": "Clear handler"
    },
    {
      "name": "showClearButton",
      "type": "boolean",
      "required": false,
      "description": "Show clear button",
      "default": "true"
    },
    {
      "name": "loading",
      "type": "boolean",
      "required": false,
      "description": "Loading state",
      "default": "false"
    }
  ],
  "Section": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "description": "The title prop."
    },
    {
      "name": "description",
      "type": "string",
      "required": false,
      "description": "The description prop."
    },
    {
      "name": "padding",
      "type": "'none' | 'sm' | 'md' | 'lg'",
      "required": false,
      "description": "Padding size"
    }
  ],
  "SegmentedControl": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "options",
      "type": "SegmentOption[]",
      "required": true,
      "description": "The options prop."
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "The value prop."
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "The onChange prop."
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "The size prop."
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "The disabled prop."
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "The aria-label prop."
    }
  ],
  "Select": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "description": "Placeholder text when no option is selected"
    },
    {
      "name": "size",
      "type": "'sm' | 'md' | 'lg'",
      "required": false,
      "description": "Select size variant"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "required": false,
      "description": "Whether to show full width",
      "default": "false"
    }
  ],
  "ShowHide": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "label",
      "type": "string",
      "required": true,
      "description": "Label for the toggle button"
    },
    {
      "name": "defaultOpen",
      "type": "boolean",
      "required": false,
      "description": "Initially expanded"
    },
    {
      "name": "open",
      "type": "boolean",
      "required": false,
      "description": "Controlled open state"
    },
    {
      "name": "onToggle",
      "type": "(open: boolean) => void",
      "required": false,
      "description": "Called when toggled"
    }
  ],
  "Skeleton": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "variant",
      "type": "SkeletonVariant",
      "required": false,
      "description": "Shape variant"
    },
    {
      "name": "width",
      "type": "string | number",
      "required": false,
      "description": "Width (CSS value, e.g. '100%', '200px')"
    },
    {
      "name": "height",
      "type": "string | number",
      "required": false,
      "description": "Height (CSS value, e.g. '20px', '1rem')"
    },
    {
      "name": "lines",
      "type": "number",
      "required": false,
      "description": "Number of skeleton lines to render (for text variant)"
    },
    {
      "name": "animate",
      "type": "boolean",
      "required": false,
      "description": "Whether to animate the skeleton"
    }
  ],
  "Spacer": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "size",
      "type": "number | string",
      "required": false,
      "description": "Fixed size in pixels or CSS value"
    },
    {
      "name": "axis",
      "type": "'horizontal' | 'vertical'",
      "required": false,
      "description": "Axis"
    }
  ],
  "Spinner": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Spinner size",
      "default": "md"
    },
    {
      "name": "variant",
      "type": "StatusVariant | 'primary'",
      "required": false,
      "description": "Spinner variant",
      "default": "info"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Loading text"
    },
    {
      "name": "centered",
      "type": "boolean",
      "required": false,
      "description": "Center spinner in container",
      "default": "false"
    }
  ],
  "Stack": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "The children prop."
    },
    {
      "name": "direction",
      "type": "'vertical' | 'horizontal'",
      "required": false,
      "description": "Direction"
    },
    {
      "name": "gap",
      "type": "number | string",
      "required": false,
      "description": "Gap in pixels or CSS value"
    },
    {
      "name": "align",
      "type": "'start' | 'center' | 'end' | 'stretch'",
      "required": false,
      "description": "Alignment"
    },
    {
      "name": "justify",
      "type": "'start' | 'center' | 'end' | 'between' | 'around'",
      "required": false,
      "description": "Justify"
    },
    {
      "name": "wrap",
      "type": "boolean",
      "required": false,
      "description": "Wrap items"
    }
  ],
  "Statistic": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "label",
      "type": "string",
      "required": true,
      "description": "The label prop."
    },
    {
      "name": "value",
      "type": "string | number",
      "required": true,
      "description": "The value prop."
    },
    {
      "name": "prefix",
      "type": "ReactNode",
      "required": false,
      "description": "Prefix (e.g. ₹, $)"
    },
    {
      "name": "suffix",
      "type": "ReactNode",
      "required": false,
      "description": "Suffix (e.g. %, units)"
    },
    {
      "name": "trend",
      "type": "{ value: number",
      "required": false,
      "description": "Trend indicator"
    }
  ],
  "Stepper": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "steps",
      "type": "StepItem[]",
      "required": true,
      "description": "Stepper steps"
    },
    {
      "name": "current",
      "type": "number",
      "required": true,
      "description": "Current step index"
    },
    {
      "name": "orientation",
      "type": "StepperOrientation",
      "required": false,
      "description": "Stepper orientation",
      "default": "horizontal"
    },
    {
      "name": "clickable",
      "type": "boolean",
      "required": false,
      "description": "Allow clicking on steps",
      "default": "false"
    },
    {
      "name": "onStepClick",
      "type": "(index: number) => void",
      "required": false,
      "description": "Step click handler"
    }
  ],
  "Switch": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Switch label text"
    },
    {
      "name": "checked",
      "type": "boolean",
      "required": false,
      "description": "Whether the switch is on"
    },
    {
      "name": "defaultChecked",
      "type": "boolean",
      "required": false,
      "description": "Default checked state for uncontrolled usage"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Size variant"
    },
    {
      "name": "onChange",
      "type": "(event: ChangeEvent<HTMLInputElement>) => void",
      "required": false,
      "description": "Change handler"
    }
  ],
  "Table": [
    {
      "name": "columns",
      "type": "TableColumn<T>[]",
      "required": true,
      "description": "Table columns configuration"
    },
    {
      "name": "data",
      "type": "T[]",
      "required": true,
      "description": "Table data rows"
    },
    {
      "name": "rowKey",
      "type": "keyof T | ((row: T, index: number) => string | number)",
      "required": false,
      "description": "Unique key extractor for rows"
    },
    {
      "name": "striped",
      "type": "boolean",
      "required": false,
      "description": "Enable row striping",
      "default": "false"
    },
    {
      "name": "hoverable",
      "type": "boolean",
      "required": false,
      "description": "Enable hover effect on rows",
      "default": "false"
    },
    {
      "name": "bordered",
      "type": "boolean",
      "required": false,
      "description": "Make table borders more prominent",
      "default": "false"
    },
    {
      "name": "compact",
      "type": "boolean",
      "required": false,
      "description": "Compact row spacing",
      "default": "false"
    },
    {
      "name": "caption",
      "type": "ReactNode",
      "required": false,
      "description": "Caption for the table (accessibility)"
    },
    {
      "name": "captionSide",
      "type": "'top' | 'bottom'",
      "required": false,
      "description": "Hide caption visually but keep for screen readers",
      "default": "false"
    },
    {
      "name": "sortState",
      "type": "SortState",
      "required": false,
      "description": "Controlled sort state"
    },
    {
      "name": "defaultSortState",
      "type": "SortState",
      "required": false,
      "description": "Default sort state for uncontrolled mode"
    },
    {
      "name": "onSortChange",
      "type": "(sortState: SortState) => void",
      "required": false,
      "description": "Sort change handler"
    },
    {
      "name": "onRowClick",
      "type": "(row: T, index: number) => void",
      "required": false,
      "description": "Row click handler"
    },
    {
      "name": "emptyState",
      "type": "ReactNode",
      "required": false,
      "description": "Empty state content"
    },
    {
      "name": "loading",
      "type": "boolean",
      "required": false,
      "description": "Loading state",
      "default": "false"
    },
    {
      "name": "loadingRows",
      "type": "number",
      "required": false,
      "description": "Number of skeleton rows to show when loading",
      "default": "5"
    },
    {
      "name": "stickyHeader",
      "type": "boolean",
      "required": false,
      "description": "Sticky header",
      "default": "false"
    },
    {
      "name": "maxHeight",
      "type": "string | number",
      "required": false,
      "description": "Maximum height for scrollable table"
    }
  ],
  "Tabs": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "items",
      "type": "TabItem[]",
      "required": true,
      "description": "Tab items"
    },
    {
      "name": "variant",
      "type": "TabsVariant",
      "required": false,
      "description": "Visual variant",
      "default": "default"
    },
    {
      "name": "orientation",
      "type": "TabsOrientation",
      "required": false,
      "description": "Tab orientation",
      "default": "horizontal"
    },
    {
      "name": "centered",
      "type": "boolean",
      "required": false,
      "description": "Center align tabs",
      "default": "false"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "required": false,
      "description": "Full width tabs",
      "default": "false"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false,
      "description": "Change handler"
    },
    {
      "name": "tabListProps",
      "type": "HTMLAttributes<HTMLDivElement>",
      "required": false,
      "description": "Additional props for tab list container"
    },
    {
      "name": "tabPanelProps",
      "type": "HTMLAttributes<HTMLDivElement>",
      "required": false,
      "description": "Additional props for tab panel container"
    },
    {
      "name": "lazy",
      "type": "boolean",
      "required": false,
      "description": "Lazy load tab content (only render active tab)",
      "default": "false"
    },
    {
      "name": "keepMounted",
      "type": "boolean",
      "required": false,
      "description": "Keep mounted (don't unmount inactive tabs)",
      "default": "false"
    }
  ],
  "Tag": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "label",
      "type": "string",
      "required": true,
      "description": "Tag label text"
    },
    {
      "name": "variant",
      "type": "StatusVariant",
      "required": false,
      "description": "Color variant"
    },
    {
      "name": "size",
      "type": "ComponentSize",
      "required": false,
      "description": "Size"
    },
    {
      "name": "icon",
      "type": "ReactNode",
      "required": false,
      "description": "Icon before label"
    },
    {
      "name": "removable",
      "type": "boolean",
      "required": false,
      "description": "Whether the tag is removable"
    },
    {
      "name": "onRemove",
      "type": "() => void",
      "required": false,
      "description": "Called when remove button is clicked"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the tag is disabled"
    }
  ],
  "Textarea": [
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Field name for form submission"
    },
    {
      "name": "id",
      "type": "string",
      "required": false,
      "description": "Field ID (links label to input)"
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is required",
      "default": "false"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "description": "Whether the field is read-only",
      "default": "false"
    },
    {
      "name": "error",
      "type": "boolean",
      "required": false,
      "description": "Error state indicator",
      "default": "false"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "required": false,
      "description": "ARIA invalid state"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "required": false,
      "description": "ARIA required state"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Whether the component is disabled",
      "default": "false"
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false,
      "description": "ARIA label for accessibility"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "required": false,
      "description": "ARIA labelled by reference"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "required": false,
      "description": "ARIA described by reference"
    },
    {
      "name": "size",
      "type": "'sm' | 'md' | 'lg'",
      "required": false,
      "description": "Textarea size variant"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "required": false,
      "description": "Whether to show full width",
      "default": "false"
    },
    {
      "name": "resize",
      "type": "boolean",
      "required": false,
      "description": "Whether to allow resizing",
      "default": "true"
    }
  ],
  "Timeline": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "items",
      "type": "TimelineItem[]",
      "required": true,
      "description": "Timeline items"
    },
    {
      "name": "mode",
      "type": "TimelineMode",
      "required": false,
      "description": "Timeline mode",
      "default": "left"
    },
    {
      "name": "reverse",
      "type": "boolean",
      "required": false,
      "description": "Reverse order",
      "default": "false"
    }
  ],
  "Toast": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "message",
      "type": "ReactNode",
      "required": true,
      "description": "Toast message"
    },
    {
      "name": "variant",
      "type": "StatusVariant",
      "required": false,
      "description": "Toast variant",
      "default": "info"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "required": false,
      "description": "Toast title"
    },
    {
      "name": "closable",
      "type": "boolean",
      "required": false,
      "description": "Show close button",
      "default": "true"
    },
    {
      "name": "duration",
      "type": "number",
      "required": false,
      "description": "Auto close duration in ms (0 to disable)",
      "default": "5000"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": false,
      "description": "Close handler"
    },
    {
      "name": "icon",
      "type": "ReactNode",
      "required": false,
      "description": "Toast icon"
    },
    {
      "name": "action",
      "type": "{ label: ReactNode",
      "required": false,
      "description": "Action button"
    },
    {
      "name": "onClick",
      "type": "() => void",
      "required": true,
      "description": "The onClick prop."
    }
  ],
  "Tooltip": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "content",
      "type": "ReactNode",
      "required": true,
      "description": "Tooltip content"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "required": true,
      "description": "Element to attach tooltip to"
    },
    {
      "name": "placement",
      "type": "TooltipPlacement",
      "required": false,
      "description": "Tooltip placement",
      "default": "top"
    },
    {
      "name": "delay",
      "type": "number",
      "required": false,
      "description": "Show delay in ms",
      "default": "200"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "description": "Disabled state",
      "default": "false"
    },
    {
      "name": "showArrow",
      "type": "boolean",
      "required": false,
      "description": "Show arrow",
      "default": "true"
    }
  ],
  "TreeView": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "nodes",
      "type": "TreeNode[]",
      "required": true,
      "description": "The nodes prop."
    },
    {
      "name": "defaultExpanded",
      "type": "string[]",
      "required": false,
      "description": "Initially expanded node IDs"
    },
    {
      "name": "onSelect",
      "type": "(id: string) => void",
      "required": false,
      "description": "Called when a node is selected"
    },
    {
      "name": "selectedId",
      "type": "string",
      "required": false,
      "description": "Selected node ID"
    }
  ],
  "VideoPlayer": [
    {
      "name": "className",
      "type": "string",
      "required": false,
      "description": "Additional CSS class names"
    },
    {
      "name": "src",
      "type": "string",
      "required": true,
      "description": "Video source URL"
    },
    {
      "name": "poster",
      "type": "string",
      "required": false,
      "description": "Poster image URL"
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "description": "Accessible title for the video"
    },
    {
      "name": "autoPlay",
      "type": "boolean",
      "required": false,
      "description": "Whether to autoplay"
    },
    {
      "name": "controls",
      "type": "boolean",
      "required": false,
      "description": "Whether to show controls"
    },
    {
      "name": "width",
      "type": "number | string",
      "required": false,
      "description": "Video width"
    },
    {
      "name": "height",
      "type": "number | string",
      "required": false,
      "description": "Video height"
    }
  ]
};
