import iconDefinitions from "./iconDefinitions.json";
import { createIconComponent } from "./createIcon";
import type { IconNodeDefinition } from "./types";

type DefinitionRecord = Record<
  string,
  {
    name: string;
    displayName: string;
    category: string;
    keywords: string[];
    nodes: IconNodeDefinition[];
  }
>;

const definitions = iconDefinitions as unknown as DefinitionRecord;

export const HomeIcon = createIconComponent(definitions.home.name, definitions.home.nodes);
export const MenuIcon = createIconComponent(definitions.menu.name, definitions.menu.nodes);
export const CloseIcon = createIconComponent(definitions.close.name, definitions.close.nodes);
export const ChevronRightIcon = createIconComponent(definitions["chevron-right"].name, definitions["chevron-right"].nodes);
export const ChevronDownIcon = createIconComponent(definitions["chevron-down"].name, definitions["chevron-down"].nodes);
export const ChevronLeftIcon = createIconComponent(definitions["chevron-left"].name, definitions["chevron-left"].nodes);
export const ChevronUpIcon = createIconComponent(definitions["chevron-up"].name, definitions["chevron-up"].nodes);
export const ArrowLeftIcon = createIconComponent(definitions["arrow-left"].name, definitions["arrow-left"].nodes);
export const ArrowRightIcon = createIconComponent(definitions["arrow-right"].name, definitions["arrow-right"].nodes);
export const ArrowUpIcon = createIconComponent(definitions["arrow-up"].name, definitions["arrow-up"].nodes);
export const ArrowDownIcon = createIconComponent(definitions["arrow-down"].name, definitions["arrow-down"].nodes);
export const SidebarLeftIcon = createIconComponent(definitions["sidebar-left"].name, definitions["sidebar-left"].nodes);
export const SearchIcon = createIconComponent(definitions.search.name, definitions.search.nodes);
export const FilterIcon = createIconComponent(definitions.filter.name, definitions.filter.nodes);
export const SortIcon = createIconComponent(definitions.sort.name, definitions.sort.nodes);
export const DownloadIcon = createIconComponent(definitions.download.name, definitions.download.nodes);
export const UploadIcon = createIconComponent(definitions.upload.name, definitions.upload.nodes);
export const EditIcon = createIconComponent(definitions.edit.name, definitions.edit.nodes);
export const DeleteIcon = createIconComponent(definitions.delete.name, definitions.delete.nodes);
export const SaveIcon = createIconComponent(definitions.save.name, definitions.save.nodes);
export const RefreshIcon = createIconComponent(definitions.refresh.name, definitions.refresh.nodes);
export const ExternalLinkIcon = createIconComponent(definitions["external-link"].name, definitions["external-link"].nodes);
export const CopyIcon = createIconComponent(definitions.copy.name, definitions.copy.nodes);
export const LinkIcon = createIconComponent(definitions.link.name, definitions.link.nodes);
export const ShareIcon = createIconComponent(definitions.share.name, definitions.share.nodes);
export const PrintIcon = createIconComponent(definitions.print.name, definitions.print.nodes);
export const PlusIcon = createIconComponent(definitions.plus.name, definitions.plus.nodes);
export const MinusIcon = createIconComponent(definitions.minus.name, definitions.minus.nodes);
export const MoreHorizontalIcon = createIconComponent(definitions["more-horizontal"].name, definitions["more-horizontal"].nodes);
export const UndoIcon = createIconComponent(definitions.undo.name, definitions.undo.nodes);
export const RedoIcon = createIconComponent(definitions.redo.name, definitions.redo.nodes);
export const MoreVerticalIcon = createIconComponent(definitions["more-vertical"].name, definitions["more-vertical"].nodes);
export const ExportIcon = createIconComponent(definitions.export.name, definitions.export.nodes);
export const ImportIcon = createIconComponent(definitions.import.name, definitions.import.nodes);
export const PlusCircleIcon = createIconComponent(definitions["plus-circle"].name, definitions["plus-circle"].nodes);
export const MinusCircleIcon = createIconComponent(definitions["minus-circle"].name, definitions["minus-circle"].nodes);
export const CheckIcon = createIconComponent(definitions.check.name, definitions.check.nodes);
export const InfoIcon = createIconComponent(definitions.info.name, definitions.info.nodes);
export const WarningIcon = createIconComponent(definitions.warning.name, definitions.warning.nodes);
export const ErrorIcon = createIconComponent(definitions.error.name, definitions.error.nodes);
export const PendingIcon = createIconComponent(definitions.pending.name, definitions.pending.nodes);
export const ApprovalIcon = createIconComponent(definitions.approval.name, definitions.approval.nodes);
export const RejectionIcon = createIconComponent(definitions.rejection.name, definitions.rejection.nodes);
export const InReviewIcon = createIconComponent(definitions["in-review"].name, definitions["in-review"].nodes);
export const CompletedIcon = createIconComponent(definitions.completed.name, definitions.completed.nodes);
export const FlagIcon = createIconComponent(definitions.flag.name, definitions.flag.nodes);
export const PauseCircleIcon = createIconComponent(definitions["pause-circle"].name, definitions["pause-circle"].nodes);
export const AlertOctagonIcon = createIconComponent(definitions["alert-octagon"].name, definitions["alert-octagon"].nodes);
export const UserIcon = createIconComponent(definitions.user.name, definitions.user.nodes);
export const UsersIcon = createIconComponent(definitions.users.name, definitions.users.nodes);
export const AddUserIcon = createIconComponent(definitions["add-user"].name, definitions["add-user"].nodes);
export const RemoveUserIcon = createIconComponent(definitions["remove-user"].name, definitions["remove-user"].nodes);
export const UserCheckIcon = createIconComponent(definitions["user-check"].name, definitions["user-check"].nodes);
export const AdminIcon = createIconComponent(definitions.admin.name, definitions.admin.nodes);
export const LockIcon = createIconComponent(definitions.lock.name, definitions.lock.nodes);
export const ShieldIcon = createIconComponent(definitions.shield.name, definitions.shield.nodes);
export const KeyIcon = createIconComponent(definitions.key.name, definitions.key.nodes);
export const ShieldCheckIcon = createIconComponent(definitions["shield-check"].name, definitions["shield-check"].nodes);
export const FingerprintIcon = createIconComponent(definitions.fingerprint.name, definitions.fingerprint.nodes);
export const UnlockIcon = createIconComponent(definitions.unlock.name, definitions.unlock.nodes);
export const NotificationIcon = createIconComponent(definitions.notification.name, definitions.notification.nodes);
export const MailIcon = createIconComponent(definitions.mail.name, definitions.mail.nodes);
export const PhoneIcon = createIconComponent(definitions.phone.name, definitions.phone.nodes);
export const MessageIcon = createIconComponent(definitions.message.name, definitions.message.nodes);
export const SendIcon = createIconComponent(definitions.send.name, definitions.send.nodes);
export const ChatIcon = createIconComponent(definitions.chat.name, definitions.chat.nodes);
export const CalendarIcon = createIconComponent(definitions.calendar.name, definitions.calendar.nodes);
export const ClockIcon = createIconComponent(definitions.clock.name, definitions.clock.nodes);
export const LocationIcon = createIconComponent(definitions.location.name, definitions.location.nodes);
export const SortAscIcon = createIconComponent(definitions["sort-asc"].name, definitions["sort-asc"].nodes);
export const SortDescIcon = createIconComponent(definitions["sort-desc"].name, definitions["sort-desc"].nodes);
export const ColumnsIcon = createIconComponent(definitions.columns.name, definitions.columns.nodes);
export const DocumentIcon = createIconComponent(definitions.document.name, definitions.document.nodes);
export const ReceiptIcon = createIconComponent(definitions.receipt.name, definitions.receipt.nodes);
export const FolderIcon = createIconComponent(definitions.folder.name, definitions.folder.nodes);
export const AttachmentIcon = createIconComponent(definitions.attachment.name, definitions.attachment.nodes);
export const ImageIcon = createIconComponent(definitions.image.name, definitions.image.nodes);
export const FileCheckIcon = createIconComponent(definitions["file-check"].name, definitions["file-check"].nodes);
export const AccessibilityIcon = createIconComponent(definitions.accessibility.name, definitions.accessibility.nodes);
export const ContrastIcon = createIconComponent(definitions.contrast.name, definitions.contrast.nodes);
export const KeyboardIcon = createIconComponent(definitions.keyboard.name, definitions.keyboard.nodes);
export const ScreenReaderIcon = createIconComponent(definitions["screen-reader"].name, definitions["screen-reader"].nodes);
export const FocusIcon = createIconComponent(definitions.focus.name, definitions.focus.nodes);
export const FontSizeIcon = createIconComponent(definitions["font-size"].name, definitions["font-size"].nodes);
export const SettingsIcon = createIconComponent(definitions.settings.name, definitions.settings.nodes);
export const HelpIcon = createIconComponent(definitions.help.name, definitions.help.nodes);
export const DashboardIcon = createIconComponent(definitions.dashboard.name, definitions.dashboard.nodes);
export const ChartIcon = createIconComponent(definitions.chart.name, definitions.chart.nodes);
export const TableIcon = createIconComponent(definitions.table.name, definitions.table.nodes);
export const ListIcon = createIconComponent(definitions.list.name, definitions.list.nodes);
export const GridIcon = createIconComponent(definitions.grid.name, definitions.grid.nodes);
export const VisibilityIcon = createIconComponent(definitions.visibility.name, definitions.visibility.nodes);
export const HideIcon = createIconComponent(definitions.hide.name, definitions.hide.nodes);
export const LanguageIcon = createIconComponent(definitions.language.name, definitions.language.nodes);
export const ServiceIcon = createIconComponent(definitions.service.name, definitions.service.nodes);
export const CertificateIcon = createIconComponent(definitions.certificate.name, definitions.certificate.nodes);
export const CaseIcon = createIconComponent(definitions.case.name, definitions.case.nodes);
export const IdCardIcon = createIconComponent(definitions["id-card"].name, definitions["id-card"].nodes);
export const StampIcon = createIconComponent(definitions.stamp.name, definitions.stamp.nodes);
export const ApplicationIcon = createIconComponent(definitions.application.name, definitions.application.nodes);
export const DatabaseIcon = createIconComponent(definitions.database.name, definitions.database.nodes);
export const ServerIcon = createIconComponent(definitions.server.name, definitions.server.nodes);
