import iconDefinitions from "./iconDefinitions.json";
import {
  AccessibilityIcon,
  AddUserIcon,
  AdminIcon,
  ApprovalIcon,
  AlertOctagonIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AttachmentIcon,
  CalendarIcon,
  CaseIcon,
  CertificateIcon,
  ChartIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  CloseIcon,
  CompletedIcon,
  ContrastIcon,
  CopyIcon,
  DashboardIcon,
  DeleteIcon,
  DocumentIcon,
  DownloadIcon,
  EditIcon,
  ErrorIcon,
  ExportIcon,
  ExternalLinkIcon,
  FlagIcon,
  FilterIcon,
  FolderIcon,
  GridIcon,
  HelpIcon,
  HideIcon,
  HomeIcon,
  IdCardIcon,
  InfoIcon,
  ImportIcon,
  InReviewIcon,
  KeyboardIcon,
  LanguageIcon,
  LinkIcon,
  ListIcon,
  LocationIcon,
  LockIcon,
  MailIcon,
  MenuIcon,
  MinusIcon,
  MinusCircleIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  NotificationIcon,
  PendingIcon,
  PauseCircleIcon,
  PhoneIcon,
  PlusIcon,
  PlusCircleIcon,
  PrintIcon,
  RefreshIcon,
  ReceiptIcon,
  RedoIcon,
  RejectionIcon,
  RemoveUserIcon,
  SaveIcon,
  ScreenReaderIcon,
  SearchIcon,
  ServiceIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  SidebarLeftIcon,
  SortIcon,
  TableIcon,
  UndoIcon,
  UploadIcon,
  UserIcon,
  UserCheckIcon,
  UsersIcon,
  VisibilityIcon,
  WarningIcon
} from "./icons";
import type { UX4GIconMetadata } from "./types";

const definitions = iconDefinitions as Record<string, UX4GIconMetadata & { nodes: unknown }>;

function serializeAttrs(attrs: Record<string, unknown>) {
  return Object.entries(attrs)
    .map(([key, value]) => `${key}="${String(value)}"`)
    .join(" ");
}

export const UX4G_ICONS = {
  home: HomeIcon,
  menu: MenuIcon,
  close: CloseIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-up": ChevronUpIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "arrow-down": ArrowDownIcon,
  "sidebar-left": SidebarLeftIcon,
  search: SearchIcon,
  filter: FilterIcon,
  sort: SortIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  edit: EditIcon,
  delete: DeleteIcon,
  save: SaveIcon,
  refresh: RefreshIcon,
  "external-link": ExternalLinkIcon,
  copy: CopyIcon,
  link: LinkIcon,
  share: ShareIcon,
  print: PrintIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  "more-horizontal": MoreHorizontalIcon,
  "more-vertical": MoreVerticalIcon,
  undo: UndoIcon,
  redo: RedoIcon,
  export: ExportIcon,
  import: ImportIcon,
  "plus-circle": PlusCircleIcon,
  "minus-circle": MinusCircleIcon,
  check: CheckIcon,
  info: InfoIcon,
  warning: WarningIcon,
  error: ErrorIcon,
  pending: PendingIcon,
  approval: ApprovalIcon,
  rejection: RejectionIcon,
  "in-review": InReviewIcon,
  completed: CompletedIcon,
  flag: FlagIcon,
  "pause-circle": PauseCircleIcon,
  "alert-octagon": AlertOctagonIcon,
  user: UserIcon,
  users: UsersIcon,
  "add-user": AddUserIcon,
  "remove-user": RemoveUserIcon,
  "user-check": UserCheckIcon,
  admin: AdminIcon,
  lock: LockIcon,
  shield: ShieldIcon,
  notification: NotificationIcon,
  mail: MailIcon,
  phone: PhoneIcon,
  calendar: CalendarIcon,
  clock: ClockIcon,
  location: LocationIcon,
  document: DocumentIcon,
  receipt: ReceiptIcon,
  folder: FolderIcon,
  attachment: AttachmentIcon,
  accessibility: AccessibilityIcon,
  contrast: ContrastIcon,
  keyboard: KeyboardIcon,
  "screen-reader": ScreenReaderIcon,
  settings: SettingsIcon,
  help: HelpIcon,
  dashboard: DashboardIcon,
  chart: ChartIcon,
  table: TableIcon,
  list: ListIcon,
  grid: GridIcon,
  visibility: VisibilityIcon,
  hide: HideIcon,
  language: LanguageIcon,
  service: ServiceIcon,
  certificate: CertificateIcon,
  case: CaseIcon,
  "id-card": IdCardIcon
} as const;

export type UX4GIconName = keyof typeof UX4G_ICONS;
export const UX4G_ICON_ALIASES = {
  trash: "delete",
  globe: "language",
  file: "document",
  files: "folder",
  "invoice": "receipt",
  "receipt-invoice": "receipt",
  workflow: "service",
  "id": "id-card",
  "idcard": "id-card",
  ellipsis: "more-horizontal",
  kebab: "more-vertical",
  approve: "approval",
  deny: "rejection",
  awaiting: "pending",
  sr: "screen-reader",
  review: "in-review",
  done: "completed",
  "invite-user": "add-user",
  "verified-user": "user-check"
} as const;

export type UX4GIconAliasName = keyof typeof UX4G_ICON_ALIASES;

export const UX4G_ICON_METADATA: Record<UX4GIconName, UX4GIconMetadata> = Object.fromEntries(
  Object.entries(definitions).map(([key, value]) => [
    key,
    {
      name: value.name,
      displayName: value.displayName,
      category: value.category,
      keywords: value.keywords
    }
  ])
) as Record<UX4GIconName, UX4GIconMetadata>;

export function resolveIconName(name: UX4GIconName | UX4GIconAliasName) {
  return (UX4G_ICON_ALIASES[name as UX4GIconAliasName] ?? name) as UX4GIconName;
}

export const UX4G_ICON_SVGS: Record<UX4GIconName, string> = Object.fromEntries(
  Object.entries(definitions).map(([key, value]) => [
    key,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n${(value.nodes as [string, Record<string, unknown>][])
      .map(([tag, attrs]) => `  <${tag} ${serializeAttrs(attrs)} />`)
      .join("\n")}\n</svg>\n`
  ])
) as Record<UX4GIconName, string>;
