export const toChildPath = (absolutePath: string): string =>
  absolutePath.startsWith("/") ? absolutePath.slice(1) : absolutePath;

export const ROUTE_PATHS = {
  FOUNDATIONS: {
    ROOT: "/foundations",
    ACCESSIBILITY: "/accessibility",
    CONTENT_SYSTEM: "/content-system",
  },
  COMPONENTS: {
    ROOT: "/components",
    FRAMEWORK_STATUS: "/framework-status",
    WEB_COMPONENTS: "/web-components",
  },
  PATTERNS: {
    LIBRARY: "/pattern-library",
    ROOT: "/patterns",
    IDENTITY_ROOT: "/patterns/identity",
    CONSENT_ROOT: "/patterns/consent",
    PAYMENT_ROOT: "/patterns/payment",
    FORMS: "/patterns/forms",
    RESILIENCE: "/patterns/resilience",
    SEARCH_DISCOVERY_ROOT: "/patterns/search-discovery",
    DASHBOARD_ROOT: "/patterns/dashboard",
    STATUS_LIFECYCLE_ROOT: "/patterns/status-lifecycle",
    NOTIFICATIONS_ROOT: "/patterns/notifications",
    CONTACT_SUPPORT_ROOT: "/patterns/contact-support",
    FEEDBACK_ROOT: "/patterns/feedback",
    LOCALIZATION_ROOT: "/patterns/localization",
    DATA_INPUT_ROOT: "/patterns/data-input",
    SERVICE: "/patterns/service",
  },
  ARCHETYPES: {
    ROOT: "/archetypes",
    APPLICATION: "/archetypes/application",
    ELIGIBILITY: "/archetypes/eligibility",
    RENEWAL: "/archetypes/renewal",
    CORRECTION: "/archetypes/correction",
    COMPLAINT: "/archetypes/complaint",
    APPROVAL: "/archetypes/approval",
    ASSISTED: "/archetypes/assisted",
    TRACKING: "/archetypes/tracking",
    APPOINTMENT: "/archetypes/appointment",
  },
  SYSTEMS: {
    ROOT: "/systems",
    MULTILINGUAL: "/systems/multilingual",
    FORM_INTELLIGENCE: "/systems/form-intelligence",
    STATE_RESILIENCE: "/systems/state-resilience",
  },
  SERVICES: {
    OVERVIEW: "/reference-service/overview",
    DEMO: "/reference-service/demo",
    SIGN_IN: "/reference-service/sign-in",
    SIGN_UP: "/reference-service/sign-up",
    FORGOT_PASSWORD: "/reference-service/forgot-password",
    VERIFY_OTP: "/reference-service/verify-otp",
    AUTH_STATUS: "/reference-service/auth-status",
    ELIGIBILITY: "/reference-service/eligibility",
    START: "/reference-service/start",
    STATUS_TRACKER: "/reference-service/status-tracker",
    DOCUMENT_UPLOAD: "/reference-service/document-upload",
    REVIEW_SUMMARY: "/reference-service/review-summary",
    DECLARATION: "/reference-service/declaration",
    USER_PROFILE: "/reference-service/user-profile",
    FORM_PERSONAL: "/reference-service/form/personal",
    FORM_ADDRESS: "/reference-service/form/address",
    FORM_ADDITIONAL: "/reference-service/form/additional",
    FORM_REVIEW: "/reference-service/form/review",
    PAYMENT_SUMMARY: "/reference-service/payment-summary",
    PAYMENT_RECEIPT: "/reference-service/payment-receipt",
    IDENTITY_SIGN_IN: "/identity/sign-in",
    IDENTITY_SIGN_UP: "/identity/sign-up",
    IDENTITY_MOBILE_OTP: "/identity/mobile-otp",
    IDENTITY_EMAIL_OTP: "/identity/email-otp",
    IDENTITY_FORGOT_PASSWORD: "/identity/forgot-password",
    IDENTITY_ACCOUNT_RECOVERY: "/identity/account-recovery",
    IDENTITY_SESSION_TIMEOUT: "/identity/session-timeout",
    IDENTITY_ERROR_LOCKOUT: "/identity/error-lockout",
    IDENTITY_AADHAAR: "/identity/aadhaar",
  },
  CERTIFICATE: {
    START: "/reference-service/certificate/start",
    ELIGIBILITY: "/reference-service/certificate/eligibility",
    HELP: "/reference-service/certificate/help",
    DOCUMENT_GUIDELINES: "/reference-service/certificate/document-guidelines",
    PRIVACY_POLICY: "/reference-service/certificate/privacy-policy",
    SIGN_IN: "/reference-service/certificate/sign-in",
    SIGN_UP: "/reference-service/certificate/sign-up",
    VERIFY_OTP: "/reference-service/certificate/verify-otp",
    FORGOT_PASSWORD: "/reference-service/certificate/forgot-password",
    SESSION_TIMEOUT: "/reference-service/certificate/session-timeout",
    USER_PROFILE: "/reference-service/certificate/user-profile",
    FORM_PERSONAL: "/reference-service/certificate/form/personal",
    FORM_ADDRESS: "/reference-service/certificate/form/address",
    FORM_ADDITIONAL: "/reference-service/certificate/form/additional",
    FORM_REVIEW: "/reference-service/certificate/form/review",
    DOCUMENT_UPLOAD: "/reference-service/certificate/document-upload",
    REVIEW_SUMMARY: "/reference-service/certificate/review-summary",
    DECLARATION: "/reference-service/certificate/declaration",
    PAYMENT_SUMMARY: "/reference-service/certificate/payment-summary",
    PAYMENT_RECEIPT: "/reference-service/certificate/payment-receipt",
    SUBMISSION_SUCCESS: "/reference-service/certificate/submission-success",
    STATUS_TRACKER: "/reference-service/certificate/status-tracker",
    NOTIFICATIONS: "/reference-service/certificate/notifications",
    MY_APPLICATIONS: "/reference-service/certificate/my-applications",
    ISSUED: "/reference-service/certificate/issued",
    FEEDBACK: "/reference-service/certificate/feedback",
    VERIFICATION: "/reference-service/certificate/verification",
    CORRECTION_REQUEST: "/reference-service/certificate/correction-request",
    REJECTED: "/reference-service/certificate/rejected",
    APPEAL: "/reference-service/certificate/appeal",
    OFFICER_DASHBOARD: "/reference-service/certificate/officer/dashboard",
    OFFICER_CASES: "/reference-service/certificate/officer/cases",
    OFFICER_REVIEW: "/reference-service/certificate/officer/review",
  },
  GOVERNANCE: {
    ROOT: "/governance",
    ADOPTION: "/governance/adoption",
    CONFORMANCE: "/governance/conformance",
    ANALYTICS: "/governance/analytics",
    SECURITY_POLICY: "/security-policy",
    CODE_OF_CONDUCT: "/code-of-conduct",
    CONTRIBUTING: "/contributing",
    COPYRIGHT: "/copyright",
    DISCLAIMER: "/disclaimer",
    PRIVACY_POLICY: "/privacy-policy",
    TERMS_OF_USE: "/terms-of-use",
    CONTACT: "/contact",
  },
} as const;
